version: 2.1

orbs:
  cypress: cypress-io/cypress@3.4.0

workflows:
  test:
    jobs:
      - cypress_run:
          filters:
            branches:
              only:
                - ci/cd

jobs:
  cypress_run:
    docker:
      - image: cypress/base:10
    working_directory: .
    steps:
      - cypress/install
      - cypress/run-tests:
          cypress-command: npx cypress run --headless
          working-directory: ./cypress
      - store_test_results:
          path: test_results/cypress