version: 2.1

orbs:
  cypress: cypress-io/cypress@3.4.0

workflows:
  test:
    jobs:
      - cypress_run

jobs:
  cypress_run:
    docker:
      - image: cypress/base:10
    working_directory: ~/repo
    steps:
      - cypress/install
      - cypress/run-tests:
          cypress-command: npx cypress run --headless
          working-directory: .
      - store_test_results: ./test_results

