version: 2.1

orbs:
  cypress: cypress-io/cypress@3.4.0

workflows:
  test:
    jobs:
      - cypress_run:
          filters:
            branches:
              only:
                - ci/cd

jobs:
  cypress_run:
    executor:
      name: cypress/default
    steps:
      - cypress/install:
          cypress-cache-key: cypress-cache-{{ arch }}-{{ checksum "package.json" }}
          cypress-cache-path: ~/.cache/Cypress
          include-branch-in-node-cache-key: false
          install-browsers: false
          install-command: ''
          node-cache-version: v1
          package-manager: npm
          post-install: ''
      - cypress/run-tests:
          cypress-command: npx cypress run --headless
          working-directory: .
      - store_test_results:
          path: test_results/cypress