version: 2.1

orbs:
  cypress: cypress-io/cypress@3.4.0

workflows:
  test:
    jobs:
      - cypress_run

jobs:
  cypress_run:
    docker:
      - image: cypress/base:10
    working_directory: ~/repo
    steps:
      - cypress/install:
          cypress-cache-key: deps-{{ checksum "package.json" }}
          cypress-cache-path: ~/.cache/Cypress
          node-cache-version: v2
      - cypress/run-tests:
          cypress-command: npx cypress run --headless
          working-directory: .
      - store_test_results: 
          path: ./test_results

